export enum MidweekSection {
    TREASURES = "TREASURES",
    MINISTRY = "MINISTRY",
    LIVING = "LIVING"
}

export enum MidweekPartType {
    TALK = "TALK",
    GEMS = "GEMS",
    BIBLE_READING = "BIBLE_READING",
    INITIAL_CALL = "INITIAL_CALL",
    RETURN_VISIT = "RETURN_VISIT",
    BIBLE_STUDY = "BIBLE_STUDY",
    EXPLAIN_BELIEFS = "EXPLAIN_BELIEFS",
    STUDENT_TALK = "STUDENT_TALK",
    WHAT_WOULD_YOU_SAY = "WHAT_WOULD_YOU_SAY",
    LIVING_ITEM = "LIVING_ITEM",
    LOCAL_NEEDS = "LOCAL_NEEDS",
    CBS = "CBS",
    CUSTOM = "CUSTOM"
}

export enum MidweekSpecialType {
    NONE = "NONE",
    CIRCUIT_OVERSEER_VISIT = "CIRCUIT_OVERSEER_VISIT",
    CIRCUIT_ASSEMBLY = "CIRCUIT_ASSEMBLY",
    REGIONAL_CONVENTION = "REGIONAL_CONVENTION",
    MEMORIAL = "MEMORIAL",
    SPECIAL_TALK = "SPECIAL_TALK",
    CUSTOM = "CUSTOM"
}

export enum MidweekRoom {
    MAIN = "MAIN",
    AUXILIARY_1 = "AUXILIARY_1",
    AUXILIARY_2 = "AUXILIARY_2"
}
