export enum Privileges {
    PUBLICADOR = "Publicador",
    ANCIAO = "Ancião",
    SM = 'Servo Ministerial',
    PIONEIROAUXILIAR = 'Pioneiro Auxiliar',
    PIONEIROREGULAR = 'Pioneiro Regular',
    PIONEIROESPECIAL = 'Pioneiro Especial',
    MISSIONARIOEMCAMPO = 'Missionário em Campo',
    AUXILIARTEMPOINDETERMINADO = 'Auxiliar por Tempo Indeterminado',
    AUXILIARINDETERMINADO = 'Auxiliar Indeterminado',
    ORADOR = "Orador",
    PRESIDENTE = 'Presidente',
    LEITOR = 'Leitor',
    DIRIGENTECAMPO = 'Dirigente de Campo',
    TESTEMUNHOPUBLICO = 'Testemunho Público',
    INDICADOR = 'Indicador',
    MICROFONEVOLANTE = 'Microfone Volante',
    SOM = 'Som',
    MIDIAS = 'Mídias',
    SOMEMIDIAS = 'Som e Mídias',
    PEDESTAL = 'Pedestal'
}

export enum PrivilegeCode {
    PUBLISHER = "PUBLISHER",
    ELDER = "ELDER",
    MINISTERIAL_SERVANT = "MINISTERIAL_SERVANT",
    REGULAR_PIONEER = "REGULAR_PIONEER",
    SPECIAL_PIONEER = "SPECIAL_PIONEER",
    MISSIONARY_WORLDWIDE = "MISSIONARY_WORLDWIDE",
    CONTINUOUS_AUXILIARY_PIONEER = "CONTINUOUS_AUXILIARY_PIONEER",
    AUXILIARY_PIONEER = "AUXILIARY_PIONEER",
    SPEAKER = "SPEAKER",
    READER = "READER",
    CHAIRMAN = "CHAIRMAN",
    ATTENDANT = "ATTENDANT",
    MICROPHONE_ATTENDANT = "MICROPHONE_ATTENDANT",
    FIELD_CONDUCTOR = "FIELD_CONDUCTOR",
    PUBLIC_WITNESS = "PUBLIC_WITNESS",
    SOUND = "SOUND",
    MEDIA = "MEDIA",
    SOUND_AND_MEDIA = "SOUND_AND_MEDIA",
    STAGE_ATTENDANT = "STAGE_ATTENDANT"
}